/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2024-03-22 07:03:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.company_005fevent;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class company_005fevent_005fPreviousEvent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/include/style.jsp", Long.valueOf(1710401481870L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1708057610423L));
    _jspx_dependants.put("jar:file:/C:/JavaStudy/final/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/aceworks/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("   rel=\"stylesheet\"\r\n");
      out.write("   integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\"\r\n");
      out.write("   crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("   integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\"\r\n");
      out.write("   crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\"\r\n");
      out.write("   integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\"\r\n");
      out.write("   crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("   src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js\"\r\n");
      out.write("   integrity=\"sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy\"\r\n");
      out.write("   crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script>\r\n");
      out.write("function deleteEvent(event_idx) {\r\n");
      out.write("    var url = 'company_event_Delete.do?event_idx=' + event_idx;\r\n");
      out.write("    window.location.href = url;\r\n");
      out.write("}\r\n");
      out.write("function updateEvent(event_idx) {\r\n");
      out.write("	var url = 'company_event_UpdateForm.do?event_idx=' + event_idx;\r\n");
      out.write("    window.location.href = url;\r\n");
      out.write("}\r\n");
      out.write("function previousEvent(event_idx,com_idx) {\r\n");
      out.write("	var url = 'company_event_PreviousEvent.do?event_idx=' + event_idx+'&com_idx='+com_idx;\r\n");
      out.write("	window.location.href = url;\r\n");
      out.write("}\r\n");
      out.write("function nextEvent(event_idx,com_idx) {\r\n");
      out.write("	var url = 'company_event_NextEvent.do?event_idx=' + event_idx+'&com_idx='+com_idx;\r\n");
      out.write("	window.location.href = url;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("#left {\r\n");
      out.write("	width: 200px;\r\n");
      out.write("	height: 1000px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	border-right: 2px solid darkblue;\r\n");
      out.write("	margin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#right {\r\n");
      out.write("	width: 900px;\r\n");
      out.write("	height: 600px;\r\n");
      out.write("	margin-left: 330px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bt {\r\n");
      out.write("	width: 180px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("#PNbt {\r\n");
      out.write("	width: 75px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h3 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("    #map {\r\n");
      out.write("        width:300px;\r\n");
      out.write("        height:300px;\r\n");
      out.write("        margin-top:10px;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>\r\n");
      out.write("	<div id=\"left\">\r\n");
      out.write("		<button id=\"bt\" type=\"button\" class=\"btn btn-outline-primary\"\r\n");
      out.write("				onclick=\"location.href='company_event_Writeform.do';\">글 작성</button>\r\n");
      out.write("		<div class=\"mt-3\"><a href=\"company_news_List.do?com_idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getCom_idx()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">회사소식</a> <br> <a href=\"company_event_List.do?com_idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getCom_idx()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">경조사</a> <br><a href=\"fileUploadForm.do\">파일업로드</a></div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"right\">\r\n");
      out.write("		\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"mt-5 mb-2\">\r\n");
      out.write("					<span class=\"h4\">임직원 경조사&gt;&gt;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDto.event_idx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("번 게시글</span>&nbsp;\r\n");
      out.write("					&nbsp;\r\n");
      out.write("					<button id=\"PNbt\" type=\"button\" class=\"btn btn-outline-dark\"\r\n");
      out.write("						onclick=\"previousEvent(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDto.event_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getCom_idx()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\">이전글</button>\r\n");
      out.write("					<button id=\"PNbt\" type=\"button\" class=\"btn btn-outline-dark\"\r\n");
      out.write("						onclick=\"nextEvent(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDto.event_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getCom_idx()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\">다음글</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<table width=\"1000\" cellspacing=\"0\" class=\"table\">\r\n");
      out.write("					<tr align=\"center\">\r\n");
      out.write("						<th class=\"table-primary\">번호</th>\r\n");
      out.write("						<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDto.event_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("						<th class=\"table-primary\">작성일</th>\r\n");
      out.write("						<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDto.event_writedate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("						\r\n");
      out.write("					<tr align=\"center\">\r\n");
      out.write("						<th class=\"table-primary\">작성자</th>\r\n");
      out.write("						<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDto.event_writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("						<th class=\"table-primary\">게시기한</th>\r\n");
      out.write("						<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDto.event_period }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th class=\"text-center table-primary\">제목</th>\r\n");
      out.write("						<td colspan=\"4\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDto.event_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th class=\"text-center table-primary\">주소</th>\r\n");
      out.write("						<td colspan=\"4\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDto.event_addr }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr height=\"400\">\r\n");
      out.write("\r\n");
      out.write("						<td colspan=\"3\" align=\"left\" valign=\"top\">\r\n");
      out.write("						");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDto.event_content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("						</td>\r\n");
      out.write("\r\n");
      out.write("						<td style=\"vertical-align: top;\">\r\n");
      out.write("						\r\n");
      out.write("				        <div class=\"d-flex justify-content-end\" style=\"height: 100%;\">\r\n");
      out.write("				            <div style=\"margin-right: 20px;\">\r\n");
      out.write("				                <h5>찾아오시는 길</h5>\r\n");
      out.write("				                <div id=\"map\"></div>\r\n");
      out.write("				            </div>\r\n");
      out.write("				        </div>\r\n");
      out.write("				        \r\n");
      out.write("					    <script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("					    <script src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=94d3da3bc59e086f2502c483efb65662&libraries=services\"></script>\r\n");
      out.write("					    <script>\r\n");
      out.write("					        var mapContainer = document.getElementById('map');\r\n");
      out.write("					        var mapOption = {\r\n");
      out.write("					            center: new daum.maps.LatLng(37.537187, 127.005476),\r\n");
      out.write("					            level: 5\r\n");
      out.write("					        };\r\n");
      out.write("					        var map = new daum.maps.Map(mapContainer, mapOption);\r\n");
      out.write("					        var geocoder = new daum.maps.services.Geocoder();\r\n");
      out.write("					        var marker = new daum.maps.Marker({\r\n");
      out.write("					            position: new daum.maps.LatLng(37.537187, 127.005476),\r\n");
      out.write("					            map: map\r\n");
      out.write("					        });\r\n");
      out.write("					\r\n");
      out.write("					        window.onload = function() {\r\n");
      out.write("					            var address = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDto.event_addr }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("					            \r\n");
      out.write("					            if (address.trim() !== '') {\r\n");
      out.write("					                geocoder.addressSearch(address, function(results, status) {\r\n");
      out.write("					                    if (status === daum.maps.services.Status.OK) {\r\n");
      out.write("					                        var result = results[0];\r\n");
      out.write("					                        var coords = new daum.maps.LatLng(result.y, result.x);\r\n");
      out.write("					                        mapContainer.style.display = \"block\";\r\n");
      out.write("					                        map.relayout();\r\n");
      out.write("					                        map.setCenter(coords);\r\n");
      out.write("					                        marker.setPosition(coords);\r\n");
      out.write("					                    }\r\n");
      out.write("					                });\r\n");
      out.write("					            }\r\n");
      out.write("					        };\r\n");
      out.write("					    </script>\r\n");
      out.write("					</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("				\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"d-flex justify-content-center\">\r\n");
      out.write("					<button id=\"bt\" type=\"button\" class=\"btn btn-outline-primary\"\r\n");
      out.write("						onclick=\"location.href='company_event_List.do?com_idx=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getCom_idx()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\">목록</button>\r\n");
      out.write("					&nbsp; &nbsp;\r\n");
      out.write("					<button id=\"bt\" type=\"button\" class=\"btn btn-outline-success\"\r\n");
      out.write("						onclick=\"updateEvent(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDto.event_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\">수정</button>\r\n");
      out.write("					&nbsp; &nbsp;\r\n");
      out.write("					<button id=\"bt\" type=\"button\" class=\"btn btn-outline-danger\"\r\n");
      out.write("						onclick=\"deleteEvent(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventDto.event_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\">삭제</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
